apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: user-state
  namespace: oiga
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: oiga
scopes:
  - registerapi
  - searchapi